env:
  es6: true
parserOptions:
  ecmaVersion: 6
parser: "@typescript-eslint/parser"
extends: "eslint:recommended"
plugins:
  - "@typescript-eslint"
rules:
  eqeqeq: ['error','always',{null: 'ignore' }]
  "@typescript-eslint/class-name-casing": 'error'
  no-console: off

