env:
  es6: true
  jest: true
  browser: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "@typescript-eslint"
rules:
  eqeqeq: ['error','always',{null: 'ignore' }]

